version: '3.1'

services:
  mssql:
    image: microsoft/mssql-server-linux
    restart: on-failure
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Paymenta2016^
    ports:
      - "1433:1433"
    healthcheck:
      #test: ["CMD", "sqlcmd" ,"ping", "-h", "localhost"]
      test: ["CMD-SHELL","/opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U sa -P Paymenta2016^ -Q \"select 1\""]
      timeout: 5s
      retries: 10