sematext-agent:
  image: 'sematext/sematext-agent-docker:latest'
  environment:
    - LOGSENE_TOKEN=1deebb05-d584-4c4d-ac05-3fdb44757742 # create a Logsene app if you don't have one yet, then use its token here and uncomment the line
    - SPM_TOKEN=84844d20-29b6-459e-94b1-97f782b73a5a
    - SPM_RECEIVER_URL=https://spm-receiver.eu.sematext.com/receiver/v1
    - LOGSENE_RECEIVER_URL=https://logsene-receiver.eu.sematext.com
    - EVENTS_RECEIVER_URL=https://apps.eu.sematext.com/event-receiver/
    - affinity:container!=*sematext-agent*
  cap_add:
    - SYS_ADMIN
  restart: always
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'